package sec04_exam_throw;

public class ThrowExample02 {
	//JVM에게 예외를 던진다.
	public static void main(String[] args) throws Exception{
	}
	
}
